INSERT INTO Multas (Mu_Codigo, Mu_Descripcion, Mu_Valor) VALUES
('M5001', 'Colocar cualquier tipo de aditamentos decorativos o no funcionales al interior o exterior del vehículo, que no han sido instalados por el fabricante original del chasis o carrocería', '100'), 
('M5003', 'Operar el vehículo con abolladuras o impactos visibles', '100'), 
('M5004', 'Polarizar total o parcialmente las ventanas laterales, frontales o posteriores.', '100'), 
('M5005', 'Carencia de iluminación o incorrecta disposición en términos de visibilidad de los ruteros frontal, lateral o posterior', '100'), 
('M5006', 'Vehículo desaseado en su exterior o interior al inicio de la jornada.', '100'), 
('M5007', 'Utilizar o modificar colores y diseños de la pintura externa del vehículo por fuera de los parámetros estándar establecidos por el ente gestor.', '100'), 
('M5008', 'Colocar propaganda no autorizada por TRANSMILENIO S.A. en los autobuses.', '100'), 
('M5009', 'Instalar luces adicionales tales como exploradoras, iluminación de chasis o de decoración, que no sean reglamentarias o instaladas por el fabricante original', '100'), 
('M5010', 'Instalar equipo de sonido al interior del vehículo no autorizado por TRANSMILENIO S.A.', '100'), 
('M5011', 'Operar con luces interiores apagadas durante el periodo nocturno.', '100'), 
('M5012', 'Operar con luces frontales, laterales y/o posteriores de iluminación o frenado imperfectas.', '100'), 
('M5013', 'Silla rota, rasgada o con falta de fijación al piso', '100'), 
('M5014', 'Sección de pasamanos desprendido, flojo o con aristas corto punzantes.', '200'), 
('M5015', 'Ventana lateral, frontal o posterior quebrada.', '200'), 
('M5016', 'Carencia de extintores especificados, falta de carga en los mismos y/o fecha vencimiento cumplida.', '200'), 
('M5017', 'Inadecuado funcionamiento de las puertas de acceso de pasajeros, ya sea por daño o incorrecto funcionamiento que afecte los tiempos de embarque y desembarque de pasajeros.', '200'), 
('M5018', 'Utilización de llantas lisas sin especificaciones de mínimo labrado establecidas por el fabricante o proveedor.', '200'), 
('M5019', 'Violar o alterar sin previa autorización del gestor el funcionamiento del sistema de control o cualquiera de sus partes.', '400'), 
('M5020', 'Inadecuado funcionamiento o daño de las puertas y escotillas de emergencia', '400'), 
('M5021', 'Funcionamiento en el interior del vehículo, de equipos de informaciones sonoras o de lectura no autorizado por TRANSMILENIO S.A.', '100'), 
('M5022', 'Transitar derramando combustible o lubricantes', '400'), 
('M5023', 'No cumplir con el Plan de Mantenimiento Preventivo y Correctivo y/o el Plan de Capacitación.', '200'), 
('M5024', 'Sin combustible', '200'), 
('M5025', 'Problemas mecánicos (tiempo de reacción 1 hora)', '200'), 
('M5026', 'No tener Expulsores para vidrios de emergencia (martillo).', '400'), 
('M5027', 'No portar el equipo de abordo para control exigido por TRANSMILENIO S.A.', '200'), 
('M5028', 'Carencia de calcomanías de emergencia e informativas', '200'), 
('M5029', 'Espejos retrovisores desperfectos', '200'), 
('M5030', 'Carencia o deterioro de logotipos, Numero del Bus e identificaciones externas: "TRANSMILENIO" ,"EMPRESA", etc.', '100'), 
('M5031', 'Operar con rines pelados, abollados, golpeados o con colores diferentes a los autorizados por TRANSMIENIO S.A.', '100'), 
('M5032', 'Operar con vidrio panorámico frontal, lateral y/o posterior fisurado.', '100'), 
('M6001', 'Vueltas perdidas', '100'), 
('M6002', 'Estacionar vehículos en las estaciones por tiempo superior al permitido.', '200'), 
('M6003', 'No parar en una estación o paradero establecido en el itinerario de operación programada de un servicio sin la previa autorización de TRANSMILENIO S.A. (Aplica para los Alimentadores).', '200'), 
('M6004', 'Parar en una estación y/o paraderos no establecido en el itinerario de operación programada de un servicio sin la previa autorización o instrucción de TRANSMILENIO S.A.', '200'), 
('M6005', 'Estacionar fuera de los lugares establecidos por TRANSMILENIO S.A..', '200'), 
('M6006', 'Recoger o dejar usuarios en puntos de la vía diferentes a los paraderos de estación y/o paradero de la ruta o servicio asignado.', '200'), 
('M6008', 'Transitar por fuera de las Vías, rutas o troncales determinadas por TRANSMILENIO S.A. sin su autorización.', '400'), 
('M6009', 'Operar en horarios o servicios que no le hayan sido autorizados por TRANSMILENIO S.A. al CONCESIONARIO.', '400'), 
('M6011', 'Alterar el recorrido de un servicio sin la previa autorización o instrucción de TRANSMILENIO S.A..', '400'), 
('M6012', 'Uso de equipo electrónico (celulares, walkman, etc.)', '100'), 
('M6013', 'Retrasar la operación', '100'), 
('M6014', 'Adelantar vehículos del mismo servicio (sin la autorización del Centro de Control respectivo aun siendo informado y este persista)', '200'), 
('M6015', 'Portar armas de cualquier naturaleza (con referencia al conductor)', '400'), 
('M6016', 'Abandono del vehículo por parte del conductor sin razón justificada', '200'), 
('M6017', 'No cumplir instrucciones de inspectores de TRANSMILENIO, personas a cargo de la operación', '400'), 
('M6018', 'Producir un accidente por acto de irresponsabilidad', '400'), 
('M6019', 'No seguir o desconocer las instrucciones dadas por autoridad policial o de tránsito', '400'), 
('M6020', 'Omitir o Negarse a dar información operacional solicitada por inspectores o personal a cargo de la operación ( el conductor)', '400'), 
('M6021', 'No portar documentación personal y/o del vehículo o portarla vencida, sin botiquín', '200'), 
('M6022', 'No usar el uniforme por parte del conductor o utilizarlo incompleto', '200'), 
('M6023', 'Deficiente presentación personal', '200'), 
('M6024', 'Pasar el semáforo en rojo (Al 2do caso el conductor sale del Sistema Integrado de Transporte Público)', '400'), 
('M6025', 'Incorrecta aproximación a las plataformas y/o paraderos asignados a la ruta o servicio.', '200'), 
('M6026', 'Transitar con exceso de velocidad', '200'), 
('M6027', 'Invasión de cebra', '200'), 
('M6028', 'Llevar acompañantes', '200'), 
('M6029', 'Conducir peligrosamente o bruscamente el vehículo con relación al frenado y al arranque poniendo en riesgo la seguridad de los pasajeros,', '200'), 
('M6030', 'Obstruir a los inspectores en el ejercicio de sus funciones', '400'), 
('M6031', 'Comprar productos a vendedores ambulantes estando en recorrido', '200'), 
('M6032', 'Dar reversa dentro de la plataforma o estación de integración sin previa autorización de TRANSMILENO S.A. (Aplica a los Alimentadores y/o zonales que operen dentro de una estación o portal del sistema).', '100'), 
('M6033', 'Hacer transbordo de pasajeros de un móvil a otro en la misma ruta sin previa autorización del centro de control zonal o de TRANSMILENIO S.A', '200'), 
('M6034', 'Cambiar de conductor en recorrido por otro conductor sin previa autorización de TRANSMILENIO S.A.', '200'), 
('M6035', 'Manejo peligroso con otro alimentador y/o particulares', '200'), 
('M6036', 'Detenerse en zonas no autorizadas para el parqueo de alimentadores (calles de aledañas a estación)', '200'), 
('M6037', 'No portar cinturón de seguridad o usarlo inadecuadamente', '200'), 
('M7001', 'Omitir el envío de información solicitada por TRANSMILENIO S.A., o enviarla por fuera de los plazos que TRANSMILENIO S.A. establezca para el efecto.( No enviar información relacionada con el sistema de programación y control de la operación)', '400'), 
('M7002', 'Oponerse a recibir en sus instalaciones personal de fiscalización de TRANSMILENIO S.A., o quien este designe, ocultarle información ó suministrar información parcial o equivocada.', '400'), 
('M7003', 'Omitir el cumplimiento de las obligaciones relacionadas con la capacitación de los conductores', '400'), 
('M7004', 'Omitir el cumplimiento de las obligaciones establecidas por el régimen laboral y de seguridad social respecto de los conductores', '400'), 
('M7005', 'Implementar prácticas administrativas y de registro contable que desvirtúen la confiabilidad de la información contable y financiera que el CONCESIONARIO se encuentra obligado a llevar conforme al presente contrato.', '400'), 
('M7006', 'Cuando se evidencie el ejercicio de prácticas flagrantes o deliberadas restrictivas de la libre competencia, o que impliquen el abuso de la posición dominante que pueda haber obtenido el CONCESIONARIO como resultado del contrato de concesión.', '400'), 
('M7007', 'Omitir las especificaciones, limitaciones de contenido o normas contenidas en los manuales y reglamentos que TRANSMILENIO S.A. Expida o haya expedido en relación con la colocación de publicidad en el interior de los buses troncales', '400'), 
('M8001', 'Permitir personal realizando ventas dentro del vehículo.', '200'), 
('M8002', 'Fumar y/o comer en el interior del vehículo (con referencia al conductor)', '100'), 
('M8003', 'Maltrato verbal o físico hacia los pasajeros o funcionarios del Sistema, agredir a supervisores o cualquier personal de la empresa operadora (con referencia al conductor)', '400'), 
('M8004', 'Colocar el vehículo en movimiento con la(s) puerta(s) abierta(s) -', '200'), 
('M8005', 'Abrir la(s) puerta(s) con el vehículo en movimiento.', '200'), 
('M8006', 'Rehusar el transporte a pasajeros sin motivo determinado en el reglamento del transporte.', '400'), 
('M8007', 'Mantener activo un conductor cuya remoción haya sido solicitada por TRANSMILENIO S.A.', '400'), 
('M8009', 'Cobrarle a los pasajeros una tarifa superior o inferior a la estipulada por TRANSMILENIO S.A., o cobrarle cualquier monto a los pasajeros des- alimentados', '400'), 
('M8010', 'Abastecer combustible con pasajeros a bordo.', '400'), 
('M8012', 'Utilizar un conductor que no esté portando su certificación de entrenamiento expedido por la empresa operadora', '200'), 
('M8013', 'Presentarse en estado de embriaguez a prestar servicio', '400'), 
('M8014', 'Cobrar tarifa a los pasajeros, en el interior de los vehículos en el sistema troncal.', '400'), 
('M8015', 'Detener el móvil en recorrido para recoger o hablar con personas fuera de éste.', '200'), 
('M8016', 'Inadecuado funcionamiento del sistema de información al interior del vehículo bien sea visual o sonoro.', '300'), 
('M8017', 'Inadecuado funcionamiento de plataforma de discapacitados.', '150'), 
('M8018', 'No contar con los buses con plataforma de discapacitados estipulados en el contrato.', '400'), 
('M8019', 'Inadecuado funcionamiento del sistema de control. (Pérdida de información entre otros).', '200'), 
('M8020', 'Inadecuado funcionamiento de las señales luminosas y sonoras de apertura y cierre de puertas.', '200'), 
('M8021', 'Falla en llantas por defectos de reencauche.', '150'), 
('M8022', 'Movilizar un bus que haya sido inmovilizado por mantenimiento sin autorización de TM.', '400'), 
('M8023', 'No cumplir con los manuales o normas de imagen del Sistema Integrado de Transporte Público en los uniformes para supervisores y conductores.', '150'), 
('M8024', 'No aplicar manejo defensivo.', '150'), 
('M8025', 'Comer y/o fumar dentro del vehículo o de la plataforma. (Aplica también para supervisores y/o personal de los concesionarios).', '200');
