INSERT INTO Inspeccion_Preguntas (IdPregunta, Pregunta)
VALUE
('1', 'Puesto del conductor: fácil acceso, y limpieza.'), 
('2', 'Angulo de visión: superior, inferior y frontal.'), 
('3', 'Estado de retrovisores: derecha, izquierda y centro.'), 
('4', 'Parasol: comprobar su estado y funcionamiento.'), 
('5', 'Control puertas: funcionamiento de cierre y apertura.'), 
('6', 'Volante: su estado y fijación.'), 
('7', 'Ventana del conductor: comprobar su funcionamiento.'), 
('8', 'Asiento del conductor: verificar el estado, fijación y posición.'), 
('9', 'Cinturón de seguridad: estado, fijación y funcionamiento.'), 
('10', 'Pedales: comprobar el estado del caucho.'), 
('11', 'Pedal de embrague: verificar condiciones de uso.'), 
('12', 'Pedal de freno: verificar condiciones de uso.'), 
('13', 'Freno de mano: verificar condiciones de uso.'), 
('14', 'Palanca de la caja: confirmación de las marchas .'), 
('15', 'Desempañador: su funcionamiento.'), 
('16', 'Limpia brisas: su funcionamiento.'), 
('17', 'Bocina: su funcionamiento.'), 
('18', 'Direccionales (derecho/izquierdo): su funcionamiento.'), 
('19', 'Luz de Parqueo y luz de reverso: su funcionamiento.'), 
('20', 'Nivel de Combustible.'), 
('21', 'Tacómetro (RPM motor).'), 
('22', 'Velocímetro.'), 
('23', 'Testigo alta temperatura motor.'), 
('24', 'Testigo baja presión de aceite.'), 
('25', 'Manómetro presión de aire .'), 
('26', 'Testigo / Alarma baja presión de aire.'), 
('27', 'Testigo alternador (Batería).'), 
('28', 'Encendido de motor.'), 
('29', 'Luz del panel.'), 
('30', 'Luces (alta y baja).'), 
('31', 'Luz de freno y reversa.'), 
('32', 'Testigo freno de parqueo.'), 
('33', 'Testigo direccionales.'), 
('34', 'Unid lógica, consola y receptor GPS.'), 
('35', 'Barreras de Control de acceso con validador de medio de pago.'), 
('36', 'Sistema de Radiocomunicaciones de datos y voz individual.'), 
('37', 'Sensores de apertura y cerrado de puertas.'), 
('38', 'Botón de pánico.'), 
('39', 'Micrófono ambiente.'), 
('40', 'Escalones de acceso: su estado y accesibilidad.'), 
('41', 'Tapa del motor: limpieza, aislamiento y su estado.'), 
('42', 'Piso: limpieza, buen estado, sin elementos sueltos o desniveles.'), 
('43', 'Sillas de pasajeros: su estado y fijación.'), 
('44', 'Sillas Preferenciales y cinturones: buen estado y señalizados (>=a 20 pasajeros). *'), 
('45', 'Pasamanos y asideros: buen estado, ajuste, sin aristas y filos.'), 
('46', 'Puertas: buen estado.'), 
('47', 'Tapizados superiores y laterales: limpieza, buen estado y ajuste.'), 
('48', 'Claraboyas: Estado, fijación, funcionamiento y señalización. *'), 
('49', 'Estructura interna carrocería: sin fisuras y corrosión.'), 
('50', 'Iluminación: funcionamiento y acrílicos en buen estado.'), 
('51', 'Paso ruedas: sin aristas y filtración de agua.'), 
('52', 'Panorámicos delantero y trasero: sin adhesivos, fisuras y filtración del agua.'), 
('53', 'Ventanas de emergencia: disposición y ubicación del elemento de expulsión o fragmentación.'), 
('54', 'Ventanas laterales: correcto funcionamiento, sin adhesivos, fisuras y filtración del agua.'), 
('55', 'Timbre: solicitud de parada'), 
('56', 'Número operacional.'), 
('57', 'Capacidad de pasajeros.'), 
('58', 'Salidas de Emerg. (señalización, instrucciones de uso).'), 
('59', 'Sillas preferenciales.'), 
('60', 'Extintor (señalización y uso).'), 
('61', 'Salidas (puertas).'), 
('62', 'Call center.'), 
('63', 'Limpia brisas: estado de las plumillas.'), 
('64', 'Vidrios: buen estado y fijación.'), 
('65', 'Placa: ajuste y legibilidad (Blanco y Negro).'), 
('66', 'Parachoques: buen estado y fijación.'), 
('67', 'Latonería y pintura: buen estado, sin impactos ni abolladuras.'), 
('68', 'Retrovisores: buen estado.'), 
('69', 'Soporte para tablas de ruta: estado y fijación.'), 
('70', 'Adhesivo número operacional: su estado y legible.'), 
('71', 'Adhesivo indicadores de accesibilidad: su estado y legible.'), 
('72', 'Luces Delimitadoras: Estado y funcionamiento.'), 
('73', 'Adhesivo servicio zonal: su estado y legible.'), 
('74', 'Latonería y pintura: buen estado, sin impactos ni abolladuras.'), 
('75', 'Puerta conductor: buen estado y funcionamiento.'), 
('76', 'Ventanas: buen estado y fijación.'), 
('77', 'Adhesivo número operacional: su estado y legible.'), 
('78', 'Adhesivo placa: su estado y legible.'), 
('79', 'Cinta Amarrilla de prevención: su estado y alineada.'), 
('80', 'Adhesivo marca del sistema: su estado y legible.'), 
('81', 'Luces Delimitadoras: Estado y funcionamiento.'), 
('82', 'Rines: su estado y con el color de la carrocería.'), 
('83', 'Adhesivo logotipo tipo de servicio (Urbano, Alimentador,Complementario,Especial): su estado y legible.'), 
('84', 'Latonería y pintura: buen estado, sin impactos ni abolladuras.'), 
('85', 'Parachoques: buen estado y fijación.'), 
('86', 'Placa: ajuste y legibilidad (Blanco y Negro).'), 
('87', 'Cinta Amarrilla de prevención: su estado y alineada.'), 
('88', 'Adhesivo número operacional: Adhesivo: su estado y legible.'), 
('89', 'Adhesivo ¿Cómo Conduzco?: su estado y legible.'), 
('90', 'Adhesivo marca del sistema: su estado y legible.'), 
('91', 'Adhesivo indicadores de accesibilidad: su estado y legible. *'), 
('92', 'Adhesivo Ceda el paso: su estado y legible.'), 
('93', 'Vidrio: buen estado y fijación.'), 
('94', 'Luces Delimitadoras: Estado y funcionamiento.'), 
('95', 'Boquilla del tubo de escape: fijación y estado.'), 
('96', 'Latonería y pintura: buen estado, sin impactos ni abolladuras.'), 
('97', 'Ventanas: buen estado y fijación.'), 
('98', 'Puertas: buen estado y funcionamiento.'), 
('99', 'Adhesivo número operacional: Adhesivo: su estado y legible.'), 
('100', 'Cinta Amarrilla de prevención: su estado y alineada.'), 
('101', 'Adhesivo placa: su estado y legible.'), 
('102', 'Adhesivo marca del sistema: su estado y legible.'), 
('103', 'Adhesivo medio de pago: su estado y legible.'), 
('104', 'Rines: su estado y con el color de la carrocería.'), 
('105', 'Luces Delimitadoras: Estado y funcionamiento.'), 
('106', 'Adhesivo indicadores de accesibilidad: su estado y legible. *'), 
('107', 'Adhesivo logotipo tipo de servicio (Urbano,Alimentador,Complementario,Especial): su estado y legible.'), 
('108', 'Frenos de disco: verificar estado general y fugas.'), 
('109', 'Frenos de campana: estado del tambor, zapatas, eje y pistón.'), 
('110', 'Zapatas de freno: verificar su desgaste.'), 
('111', 'Eje leva S: verificar estado y lubricación.'), 
('112', 'Bombonas: verificar estado general y fugas (susp. Neu). *'), 
('113', 'Topes de la suspensión: verificar su estado y sin grietas.'), 
('114', 'Ballestas: verificar abrazaderas, hojas y articulaciones.'), 
('115', 'Amortiguadores: verificar desgaste en los bujes y fugas.'), 
('116', 'Soportes de amortiguadores: Verificar su estado.'), 
('117', 'Caja de dirección: verificar holgura.'), 
('118', 'Tubería de la dirección: Verificar fugas.'), 
('119', 'Apoyo caja de la dirección: verificar fisuras.'), 
('120', 'Brazo pitman: verificar holgura.'), 
('121', 'Barra de dirección: verificar holgura en los terminales.'), 
('122', 'Barras de unión: verificar holgura en los terminales.'), 
('123', 'Estabilizadoras: verificar holgura en los terminales.'), 
('124', 'Estabilizadoras: verificar fisuras, desgaste de los bujes.'), 
('125', 'Eje delantero: verificar su estado.'), 
('126', 'Pivote de mangueta: verificar su estado y lubricación.'), 
('127', 'Barra de reacción: verificar holgura y fis. de los cojinetes.'), 
('128', 'Válvula niveladora: verificar el estado y fugas (susp.neu). *'), 
('129', 'Llantas: Condiciones de uso, verificar estado y medir labrado (minimo 2mm).'), 
('130', 'Rines: verificar su estado, fisuras y sin abolladuras.'), 
('131', 'Caja de velocidades: verificar: fugas, fijación y gomas.'), 
('132', 'Verificar guarda polvo acople de la caja.'), 
('133', 'Cilindro del embrague: verificar estado y fugas.'), 
('134', 'Diferencial: verificar fugas y sello del piñón.'), 
('135', 'Crucetas y Cardan: verificar su estado y lubricación.'), 
('136', 'Bombonas: verificar estado general y fugas (susp. Neu).'), 
('137', 'Ballestas: verificar abrazaderas, hojas y articulaciones.'), 
('138', 'Amortiguadores: verificar desgaste en los bujes y fugas.'), 
('139', 'Soportes de amortiguadores: Verificar su estado.'), 
('140', 'Estabilizadoras: verificar holgura en los terminales.'), 
('141', 'Estabilizadoras: verificar fisuras, desgaste de los bujes.'), 
('142', 'Barra de reacción: verificar holgura y fisuras de los cojinetes (susp. Neu).'), 
('143', 'Frenos de disco: verificar estado general y fugas.'), 
('144', 'Frenos de campana: estado del tambor, zapatas, eje y pistón.'), 
('145', 'Zapatas de freno: verificar su desgaste.'), 
('146', 'Eje leva S: verificar estado y lubricación.'), 
('147', 'Tanques de aire: verificar fugas y su fijación.'), 
('148', 'Catalizador y Escape: verificar su estado, fisuras y soportes.'), 
('149', 'Llantas: Condiciones de uso, verificar estado y medir labrado (minimo 2mm).'), 
('150', 'Rines: verificar su estado, fisuras y sin abolladuras.'), 
('151', 'Motor: verificar estado del aislamiento térmico y acústico.'), 
('152', 'Motor: verificar fugas en general (aceite y agua).'), 
('153', 'Turbo: verificar fugas de aceite y gases.'), 
('154', 'Soportes del motor: verificar gomas y su fijación.'), 
('155', 'Correa: verificar estado y alineación.'), 
('156', 'Tensor y poleas: verificar holgura y rodamiento.'), 
('157', 'Admisión de aire: verificar fuga y estado general.'), 
('158', 'Radiador: verificar su estado, limpieza y fugas.'), 
('159', 'Mangueras / tubos en general: verificar fugas y fricciones.'), 
('160', 'Bomba de agua: verificar fugas.'), 
('161', 'Filtro de aire: verificar estado y saturación.'), 
('162', 'Ductos de combustible: verificar fugas y fricción.'), 
('163', 'Chasis general : su estado, sin grietas y su lubricación.'), 
('164', 'Central eléctrica: verificar relés, cabos y conexiones.'), 
('165', 'Cables eléctricos en general: verificar su estado y protección.'), 
('166', 'Baterías: verificar fugas, bornes sulfatados y limpieza.'), 
('167', 'Deposito de combustible: fisuras, fugas y tapa cerrada.'), 
('168', 'Elevador o rampa para discapacitados: verificar estado y funcionamiento.');
